import Head from 'next/head';
import Image from 'next/image';
import styles from '../../styles/Home.module.scss';

export default function Home() {
  return (
    <>
      <Head>
        <title>Home | IgNews</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <div className={styles.container}></div>
    </>
  );
}
